<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PhoneBook.DataAccess\PhoneBook.DataAccess.csproj" />
    <ProjectReference Include="..\PhoneBook.Core\PhoneBook.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    
  <PackageReference Include="AutoMapper" Version="12.0.1" />


  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
